version: '3'
services:
  starleta-backend:
    build:
      context: .
      dockerfile: devops/Dockerfile
    #command: gunicorn -b 0.0.0.0:8000 aulapp.aulapp.wsgi:application
    ports:
      - "8003:8003"